# Generated by Django 5.1.6 on 2025-05-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
